name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven   # change to "gradle" if you use Gradle

      - name: Build & test with Maven
        run: mvn -B -ntp clean test

      # Optional gate: fail if JaCoCo coverage < 80 %
      # Uncomment if you have the jacoco-maven-plugin configured
      # - name: Enforce 80 % coverage
      #   run: |
      #     mvn -q jacoco:report
      #     COVERED=$(grep -Po '(?<=<counter type="INSTRUCTION" missed="\\d+" covered=")\\d+' target/site/jacoco/jacoco.xml)
      #     echo "Covered=$COVERED"
      #     if [ "$COVERED" -lt 80 ]; then
      #       echo "Coverage below 80 % — failing build."
      #       exit 1
      #     fi
