name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # All `run:` steps will execute from the inner Maven folder
    defaults:
      run:
        working-directory: slot_gui_project/slot_gui_project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: none     # disable caching so it won’t look for pom.xml at the repo root

      - name: Build & test with Maven
        run: mvn -B -ntp clean test
